all:
	gcc -o char char.c
	gcc -o gets gets.c 
	gcc -o sizeof_char sizeof_char.c
	gcc -o wchar wchar.c 
	gcc -o strcpy8888888811111111 strcpy.c
clean:
	rm char gets sizeof_char wchar strcpy8888888811111111

